spring:
  #MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/testing?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root


  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#logging.level.org.springframework.web=DEBUG
logging:
  level:
    org:
      springframework:
        web: DEBUG

  # H2 Web Console (H2ConsoleProperties)
hibernate:
  hbm2ddl:
    auto: create